Document: backports
Title: Debian backports Manual
Author: <insert document author here>
Abstract: This manual describes what backports is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/backports/backports.sgml.gz

Format: postscript
Files: /usr/share/doc/backports/backports.ps.gz

Format: text
Files: /usr/share/doc/backports/backports.text.gz

Format: HTML
Index: /usr/share/doc/backports/html/index.html
Files: /usr/share/doc/backports/html/*.html
